// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EditMenu(arg1:Array<main.PlatForm>):Promise<void>;

export function GetVersion():Promise<string>;

export function ReadMenu():Promise<Array<main.PlatForm>>;

export function ReadSetting():Promise<main.Setting>;

export function SideMode():Promise<void>;

export function WindowMode():Promise<void>;

export function WriteHome(arg1:string):Promise<void>;

export function WriteLastPage(arg1:string):Promise<void>;

export function WriteSetting(arg1:main.Setting):Promise<void>;
