// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EditMenu(arg1) {
  return window['go']['main']['App']['EditMenu'](arg1);
}

export function ReadMenu() {
  return window['go']['main']['App']['ReadMenu']();
}

export function WriteHome(arg1) {
  return window['go']['main']['App']['WriteHome'](arg1);
}
