// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EditMenu(arg1) {
  return window['go']['main']['App']['EditMenu'](arg1);
}

export function ExportPlatfrom() {
  return window['go']['main']['App']['ExportPlatfrom']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportPlatfrom() {
  return window['go']['main']['App']['ImportPlatfrom']();
}

export function ReadMenu() {
  return window['go']['main']['App']['ReadMenu']();
}

export function ReadSetting() {
  return window['go']['main']['App']['ReadSetting']();
}

export function SideMode() {
  return window['go']['main']['App']['SideMode']();
}

export function WindowMode() {
  return window['go']['main']['App']['WindowMode']();
}

export function WriteHome(arg1) {
  return window['go']['main']['App']['WriteHome'](arg1);
}

export function WriteLastPage(arg1) {
  return window['go']['main']['App']['WriteLastPage'](arg1);
}

export function WriteSetting(arg1) {
  return window['go']['main']['App']['WriteSetting'](arg1);
}
