// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EditMenu(arg1:Array<main.PlatForm>):Promise<void>;

export function ReadMenu():Promise<Array<main.PlatForm>>;

export function WriteHome(arg1:string):Promise<void>;
